### ISSUE TITLE
undefined method `with_indifferent_access' for {:shortname=>"shortname"}:Hash

### ISSUE THREAD

**Issue by arcadiy** [simonrice/middleman-disqus#10]
I'm trying to get the middleman-disqus gem up and running, and I think I have some environmental issues that are preventing the extension from working.

When I try to load a page with disqus comments enabled using the disqus helper in ERB (<%= disqus %>) I get the NoMethodError in the subject. It's failing in extension.rb on the line:

    @@options.to_h.merge(options).with_indifferent_access

A bit of Googling seems to suggest that with_indifferent_access is a method provided by the activesupport gem, which I think is just a dependency of the raw Middleman code. It's certainly in the Gemfile.lock file.

So, I'm a bit stumped by what's causing the error. I'm using Ruby 2.1.2 at the moment. Any ideas?

**Comment by simonrice** [comment]
I finally got around to updating the middleman dependency to 3.3 in v1.1 - I hope this all works now!
