### ISSUE TITLE
middleman 4

### ISSUE THREAD

**Issue by hovancik** [simonrice/middleman-disqus#13]
```
Bundler could not find compatible versions for gem "middleman-core":
  In snapshot (Gemfile.lock):
    middleman-core (4.0.0)

  In Gemfile:
    middleman-disqus (~> 1.1) ruby depends on
      middleman-core (~> 3.3) ruby

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

I fixed it by setting `s.add_runtime_dependency("middleman-core", [">= 3.3"])` , tests are failing, thought. Didn't investigate further, as it seems to work fine for me.

**Comment by simonrice** [comment]
Middleman 4.x support is indeed well worth adding now it's been released!  I'll see what I can do here!

**Comment by JohannaE** [comment]
middleman 4.x support would be nice.

I could not get this extension to run with middleman 4 and middleman-blog 4.0

**Comment by hovancik** [comment]
@JohannaE I am using middleman 4 and blog as well and I made it work for me

It works fine in https://github.com/DiscoverBSD/talks by using forked repo https://github.com/hovancik/middleman-disqus

I believe the only change I've done was in gemfile: `gem 'middleman-disqus', github: 'hovancik/middleman-disqus'`

**Comment by JohannaE** [comment]
Thanks it works :+1:

**Comment by simonrice** [comment]
I am working on a new version with passing tests (based on RSpec/Capybara rather than Cucumber) ✅ this should be ready to give a spin in a few days 😀 my changes are currently on the feature/middleman4 branch.

**Comment by simonrice** [comment]
All of my changes have been pushed to master & I'll be releasing v1.2 soon, so feel free to give it a spin.

**Comment by hovancik** [comment]
master branch works fine for me

**Comment by simonrice** [comment]
v1.2 is now released 🚀 thank you for all of your help!
